$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

PROVISIONING_PROFILE = FileList['provisioning/*.mobile*'].first

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'rotation'
  app.provisioning_profile = PROVISIONING_PROFILE
end
